name: Deploy FastAPI Backend

# This tells GitHub to only run the pipeline when code is pushed to the main branch
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**' # Only triggers if files in the backend folder change
      - '.github/workflows/deploy-backend.yml'
      - 'requirements-backend.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use stable Python 3.11

      - name: Install Dependencies and Create Zip
        run: |
          cd backend
          
          # Force pip to download Amazon Linux compatible binaries instead of Ubuntu ones
          pip install \
            --platform manylinux2014_x86_64 \
            --target=./ \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --upgrade \
            -r requirements-backend.txt
            
          zip -r9 deployment_package.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this if your Lambda is in a different region

      - name: Upload Zip to S3 Staging
        run: |
          aws s3 cp deployment_package.zip s3://nutriplan-deployment/deployment_package.zip

      - name: Tell Lambda to Pull from S3
        run: |
          aws lambda update-function-code \
            --function-name NutriPlan-backend \
            --s3-bucket nutriplan-deployment \
            --s3-key deployment_package.zip